//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winTelDefteriWithEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int ID { get; set; }
        public string AdresTanim { get; set; }
        public int KisiID { get; set; }
    
        public virtual Kisi Kisi { get; set; }
    }
}
